const skills = {
  agility: [
    {
      name: "Gnome Stronghold Agility Course",
      level: 1,
      experience: 86.5,
      link:
        "https://oldschool.runescape.wiki/w/Gnome_Stronghold_Agility_Course",
    },
    {
      name: "Draynor Village Rooftop Course",
      level: 10,
      experience: 120,
      link: "https://oldschool.runescape.wiki/w/Draynor_Village_Rooftop_Course",
    },
    {
      name: "Al Kharid Rooftop Course",
      level: 20,
      experience: 180,
      link: "https://oldschool.runescape.wiki/w/Al_Kharid_Rooftop_Course",
    },
    {
      name: "Werewolf Skullball",
      level: 25,
      experience: 750,
      link: "https://oldschool.runescape.wiki/w/Werewolf_Skullball",
    },
    {
      name: "Varrock Rooftop Course",
      level: 30,
      experience: 238,
      link: "https://oldschool.runescape.wiki/w/Varrock_Rooftop_Course",
    },
    {
      name: "Penguin Agility Course",
      level: 30,
      experience: 540,
      link: "https://oldschool.runescape.wiki/w/Penguin_Agility_Course",
    },
    {
      name: "Agility Pyramid",
      level: 30,
      experience: 1030,
      link: "https://oldschool.runescape.wiki/w/Agility_Pyramid",
    },
    {
      name: "Barbarian Outpost Agility Course",
      level: 35,
      experience: 153.3,
      link:
        "https://oldschool.runescape.wiki/w/Barbarian_Outpost_Agility_Course",
    },
    {
      name: "Canifis Rooftop Course",
      level: 40,
      experience: 240,
      link: "https://oldschool.runescape.wiki/w/Canifis_Rooftop_Course",
    },
    {
      name: "Ape Atoll Agility Course",
      level: 48,
      experience: 580,
      link: "https://oldschool.runescape.wiki/w/Ape_Atoll_Agility_Course",
    },
    {
      name: "Falador Rooftop Course",
      level: 50,
      experience: 440,
      link: "https://oldschool.runescape.wiki/w/Falador_Rooftop_Course",
    },
    {
      name: "Wilderness Agility Course",
      level: 52,
      experience: 571.4,
      link: "https://oldschool.runescape.wiki/w/Wilderness_Agility_Course",
    },
    {
      name: "Seers' Village Rooftop Course",
      level: 60,
      experience: 570,
      link:
        "https://oldschool.runescape.wiki/w/Seers%27_Village_Rooftop_Course",
    },
    {
      name: "Werewolf Agility Course",
      level: 60,
      experience: 730,
      link: "https://oldschool.runescape.wiki/w/Werewolf_Agility_Course",
    },
    {
      name: "Pollnivneach Rooftop Course",
      level: 70,
      experience: 890,
      link: "https://oldschool.runescape.wiki/w/Pollnivneach_Rooftop_Course",
    },
    {
      name: "Dorgesh-Kaan Agility Course",
      level: 70,
      experience: 2750,
      link: "https://oldschool.runescape.wiki/w/Dorgesh-Kaan_Agility_Course",
    },
    {
      name: "Prifddinas Agility Course",
      level: 75,
      experience: 1285.2,
      link: "https://oldschool.runescape.wiki/w/Prifddinas_Agility_Course",
    },
    {
      name: "Rellekka Rooftop Course",
      level: 80,
      experience: 780,
      link: "https://oldschool.runescape.wiki/w/Rellekka_Rooftop_Course",
    },
    {
      name: "Ardougne Rooftop Course",
      level: 90,
      experience: 793,
      link: "https://oldschool.runescape.wiki/w/Ardougne_Rooftop_Course",
    },
  ],
  construction: [],
  cooking: [
    {
      name: "Anchovies",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Anchovies",
    },
    {
      name: "Cooked Chicken",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Cooked_chicken",
    },
    {
      name: "Cooked Meat",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Cooked_meat",
    },
    {
      name: "Cooked Rabbit",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Cooked_rabbit",
    },
    {
      name: "Shrimps",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Shrimps",
    },
    {
      name: "Bread",
      level: 1,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Bread",
    },
    {
      name: "Sardine",
      level: 1,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Sardine",
    },
    {
      name: "Herring",
      level: 5,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Herring",
    },
    {
      name: "Fruit Blast",
      level: 6,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Fruit_blast",
    },
    {
      name: "Baked Potato",
      level: 7,
      experience: 15,
      link: "https://oldschool.runescape.wiki/w/Baked_potato",
    },
    {
      name: "Mackerel",
      level: 10,
      experience: 60,
      link: "https://oldschool.runescape.wiki/w/Mackerel",
    },
    {
      name: "Redberry Pie",
      level: 10,
      experience: 78,
      link: "https://oldschool.runescape.wiki/w/Redberry_pie",
    },
    {
      name: "Trout",
      level: 15,
      experience: 70,
      link: "https://oldschool.runescape.wiki/w/Trout",
    },
    {
      name: "Cod",
      level: 18,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Cod",
    },
    {
      name: "Pike",
      level: 20,
      experience: 80,
      link: "https://oldschool.runescape.wiki/w/Pike",
    },
    {
      name: "Meat Pie",
      level: 20,
      experience: 104,
      link: "https://oldschool.runescape.wiki/w/Meat_pie",
    },
    {
      name: "Salmon",
      level: 25,
      experience: 90,
      link: "https://oldschool.runescape.wiki/w/Salmon",
    },
    {
      name: "Stew",
      level: 25,
      experience: 117,
      link: "https://oldschool.runescape.wiki/w/Stew",
    },
    {
      name: "Tuna",
      level: 30,
      experience: 100,
      link: "https://oldschool.runescape.wiki/w/Tuna",
    },
    {
      name: "Apple Pie",
      level: 30,
      experience: 130,
      link: "https://oldschool.runescape.wiki/w/Apple_pie",
    },
    {
      name: "Cooked Karambwan",
      level: 30,
      experience: 190,
      link: "https://oldschool.runescape.wiki/w/Cooked_karambwan",
    },
    {
      name: "Plain Pizza",
      level: 35,
      experience: 143,
      link: "https://oldschool.runescape.wiki/w/Plain_pizza",
    },
    {
      name: "Jug of Wine",
      level: 35,
      experience: 200,
      link: "https://oldschool.runescape.wiki/w/Jug_of_wine",
    },
    {
      name: "Potato with Butter",
      level: 39,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Potato_with_butter",
    },
    {
      name: "Lobster",
      level: 40,
      experience: 120,
      link: "https://oldschool.runescape.wiki/w/Lobster",
    },
    {
      name: "Cake",
      level: 40,
      experience: 180,
      link: "https://oldschool.runescape.wiki/w/Cake",
    },
    {
      name: "Swordfish",
      level: 45,
      experience: 140,
      link: "https://oldschool.runescape.wiki/w/Swordfish",
    },
    {
      name: "Meat Pizza",
      level: 45,
      experience: 169,
      link: "https://oldschool.runescape.wiki/w/Meat_pizza",
    },
    {
      name: "Potato with Cheese",
      level: 47,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Potato_with_cheese",
    },
    {
      name: "Chocolate Cake",
      level: 50,
      experience: 210,
      link: "https://oldschool.runescape.wiki/w/Chocolate_cake",
    },
    {
      name: "Anchovy Pizza",
      level: 55,
      experience: 182,
      link: "https://oldschool.runescape.wiki/w/Anchovy_pizza",
    },
    {
      name: "Monkfish",
      level: 62,
      experience: 150,
      link: "https://oldschool.runescape.wiki/w/Monkfish",
    },
    {
      name: "Pineapple Pizza",
      level: 65,
      experience: 195,
      link: "https://oldschool.runescape.wiki/w/Pineapple_pizza",
    },
    {
      name: "Wine Of Zamorak",
      level: 65,
      experience: 200,
      link: "https://oldschool.runescape.wiki/w/Wine_of_zamorak",
    },
    {
      name: "Shark",
      level: 80,
      experience: 210,
      link: "https://oldschool.runescape.wiki/w/Shark",
    },
    {
      name: "Anglerfish",
      level: 84,
      experience: 230,
      link: "https://oldschool.runescape.wiki/w/Anglerfish",
    },
    {
      name: "Manta Ray",
      level: 91,
      experience: 216.2,
      link: "https://oldschool.runescape.wiki/w/Manta_ray",
    },
  ],
  combat: [],
  crafting: [],
  farming: [],
  firemaking: [
    {
      name: "Logs",
      level: 1,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Logs",
    },
    {
      name: "Pyre Logs",
      level: 5,
      experience: 50.5,
      link: "https://oldschool.runescape.wiki/w/Pyre_logs",
    },
    {
      name: "Oak Logs",
      level: 15,
      experience: 60,
      link: "https://oldschool.runescape.wiki/w/Oak_logs",
    },
    {
      name: "Oak Pyre Logs",
      level: 20,
      experience: 70,
      link: "https://oldschool.runescape.wiki/w/Oak_pyre_logs",
    },
    {
      name: "Willow Logs",
      level: 30,
      experience: 90,
      link: "https://oldschool.runescape.wiki/w/Willow_logs",
    },
    {
      name: "Willow Pyre Logs",
      level: 35,
      experience: 100,
      link: "https://oldschool.runescape.wiki/w/Willow_pyre_logs",
    },
    {
      name: "Teak Logs",
      level: 35,
      experience: 105,
      link: "https://oldschool.runescape.wiki/w/Teak_logs",
    },
    {
      name: "Teak Pyre Logs",
      level: 40,
      experience: 120,
      link: "https://oldschool.runescape.wiki/w/Teak_pyre_logs",
    },
    {
      name: "Maple Logs",
      level: 45,
      experience: 135,
      link: "https://oldschool.runescape.wiki/w/Maple_logs",
    },
    {
      name: "Maple Pyre Logs",
      level: 50,
      experience: 175,
      link: "https://oldschool.runescape.wiki/w/Maple_pyre_logs",
    },
    {
      name: "Mahogany Logs",
      level: 50,
      experience: 157.5,
      link: "https://oldschool.runescape.wiki/w/Mahogany_logs",
    },
    {
      name: "Mahogany Pyre Logs",
      level: 55,
      experience: 210,
      link: "https://oldschool.runescape.wiki/w/Mahogany_pyre_logs",
    },
    {
      name: "Yew Logs",
      level: 60,
      experience: 202.5,
      link: "https://oldschool.runescape.wiki/w/Yew_logs",
    },
    {
      name: "Yew Pyre Logs",
      level: 65,
      experience: 225,
      link: "https://oldschool.runescape.wiki/w/Yew_pyre_logs",
    },
    {
      name: "Magic Logs",
      level: 75,
      experience: 303.8,
      link: "https://oldschool.runescape.wiki/w/Magic_logs",
    },
    {
      name: "Magic Pyre Logs",
      level: 80,
      experience: 404.5,
      link: "https://oldschool.runescape.wiki/w/Magic_pyre_logs",
    },
    {
      name: "Redwood Logs",
      level: 90,
      experience: 350,
      link: "https://oldschool.runescape.wiki/w/Redwood_logs",
    },
    {
      name: "Redwood Pyre Logs",
      level: 95,
      experience: 500,
      link: "https://oldschool.runescape.wiki/w/Redwood_pyre_logs",
    },
  ],
  fishing: [],
  fletching: [],
  herblore: [],
  hunter: [],
  magic: [],
  mining: [
    {
      name: "Clay",
      level: 1,
      experience: 5,
      link: "https://oldschool.runescape.wiki/w/Clay",
    },
    {
      name: "Rune Essence",
      level: 1,
      experience: 5,
      link: "https://oldschool.runescape.wiki/w/Rune_essence",
    },
    {
      name: "Copper Ore",
      level: 1,
      experience: 17.5,
      link: "https://oldschool.runescape.wiki/w/Copper_ore",
    },
    {
      name: "Tin Ore",
      level: 1,
      experience: 17.5,
      link: "https://oldschool.runescape.wiki/w/Tin_ore",
    },
    {
      name: "Limestone",
      level: 10,
      experience: 26.5,
      link: "https://oldschool.runescape.wiki/w/Limestone",
    },
    {
      name: "Iron Ore",
      level: 15,
      experience: 35,
      link: "https://oldschool.runescape.wiki/w/Iron_ore",
    },
    {
      name: "Silver Ore",
      level: 20,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Silver_ore",
    },
    {
      name: "Pure Essence",
      level: 30,
      experience: 5,
      link: "https://oldschool.runescape.wiki/w/Pure_essence",
    },
    {
      name: "Coal",
      level: 30,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Coal",
    },
    {
      name: "Pay-dirt",
      level: 30,
      experience: 60,
      link: "https://oldschool.runescape.wiki/w/Pay-dirt",
    },
    {
      name: "Sandstone (1kg)",
      level: 35,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Sandstone_(1kg)",
    },
    {
      name: "Sandstone (2kg)",
      level: 35,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Sandstone_(2kg)",
    },
    {
      name: "Sandstone (5kg)",
      level: 35,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Sandstone_(5kg)",
    },
    {
      name: "Sandstone (10kg)",
      level: 35,
      experience: 60,
      link: "https://oldschool.runescape.wiki/w/Sandstone_(10kg)",
    },
    {
      name: "Dense Essence Block",
      level: 38,
      experience: 12,
      link: "https://oldschool.runescape.wiki/w/Dense_essence_block",
    },
    {
      name: "Gem Rock",
      level: 40,
      experience: 65,
      link: "https://oldschool.runescape.wiki/w/Gem_rock",
    },
    {
      name: "Gold Ore",
      level: 40,
      experience: 65,
      link: "https://oldschool.runescape.wiki/w/Gold_ore",
    },
    {
      name: "Mithril Ore",
      level: 55,
      experience: 80,
      link: "https://oldschool.runescape.wiki/w/Mithril_ore",
    },
    {
      name: "Lovakite Ore",
      level: 65,
      experience: 10,
      link: "https://oldschool.runescape.wiki/w/Lovakite_ore",
    },
    {
      name: "Adamantite Ore",
      level: 70,
      experience: 95,
      link: "https://oldschool.runescape.wiki/w/Adamantite_ore",
    },
    {
      name: "Runite Ore",
      level: 85,
      experience: 125,
      link: "https://oldschool.runescape.wiki/w/Runite_ore",
    },
    {
      name: "Amethyst",
      level: 92,
      experienec: 240,
      link: "https://oldschool.runescape.wiki/w/Amethyst",
    },
  ],
  prayer: [
    {
      name: "Bones",
      level: 1,
      experience: 4.5,
      link: "https://oldschool.runescape.wiki/w/Bones",
    },
    {
      name: "Monkey Bones",
      level: 1,
      experience: 5,
      link: "https://oldschool.runescape.wiki/w/Monkey_bones",
    },
    {
      name: "Bat Bones",
      level: 1,
      experience: 5.3,
      link: "https://oldschool.runescape.wiki/w/Bat_bones",
    },
    {
      name: "Big Bones",
      level: 1,
      experience: 15,
      link: "https://oldschool.runescape.wiki/w/Big_bones",
    },
    {
      name: "Jogre Bones",
      level: 1,
      experience: 15,
      link: "https://oldschool.runescape.wiki/w/Jogre_bones",
    },
    {
      name: "Zogre Bones",
      level: 1,
      experience: 22.5,
      link: "https://oldschool.runescape.wiki/w/Zogre_bones",
    },
    {
      name: "Shaikahan Bones",
      level: 1,
      experience: 25,
      link: "https://oldschool.runescape.wiki/w/Shaikahan_bones",
    },
    {
      name: "Babydragon Bones",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Babydragon_bones",
    },
    {
      name: "Wyrm Bones",
      level: 1,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Wyrm_bones",
    },
    {
      name: "Dragon Bones",
      level: 1,
      experience: 72,
      link: "https://oldschool.runescape.wiki/w/Dragon_bones",
    },
    {
      name: "Wyvern Bones",
      level: 1,
      experience: 72,
      link: "https://oldschool.runescape.wiki/w/Wyvern_bones",
    },
    {
      name: "Drake Bones",
      level: 1,
      experience: 80,
      link: "https://oldschool.runescape.wiki/w/Drake_bones",
    },
    {
      name: "Fayrg Bones",
      level: 1,
      experience: 84,
      link: "https://oldschool.runescape.wiki/w/Fayrg_bones",
    },
    {
      name: "Lava Dragon Bones",
      level: 1,
      experience: 85,
      link: "https://oldschool.runescape.wiki/w/Lava_dragon_bones",
    },
    {
      name: "Raurg Bones",
      level: 1,
      experience: 96,
      link: "https://oldschool.runescape.wiki/w/Raurg_bones",
    },
    {
      name: "Hydra Bones",
      level: 1,
      experience: 110,
      link: "https://oldschool.runescape.wiki/w/Hydra_bones",
    },
    {
      name: "Dagannoth Bones",
      level: 1,
      experience: 125,
      link: "https://oldschool.runescape.wiki/w/Dagannoth_bones",
    },
    {
      name: "Ourg Bones",
      level: 1,
      experience: 140,
      link: "https://oldschool.runescape.wiki/w/Ourg_bones",
    },
    {
      name: "Ensouled Goblin Head",
      level: 1,
      experience: 130,
      link: "https://oldschool.runescape.wiki/w/Ensouled_goblin_head",
    },
    {
      name: "Ensouled Monkey Head",
      level: 1,
      experience: 182,
      link: "https://oldschool.runescape.wiki/w/Ensouled_monkey_head",
    },
    {
      name: "Ensouled Imp Head",
      level: 1,
      experience: 286,
      link: "https://oldschool.runescape.wiki/w/Ensouled_imp_head",
    },
    {
      name: "Ensouled Minotaur Head",
      level: 1,
      experience: 364,
      link: "https://oldschool.runescape.wiki/w/Ensouled_minotaur_head",
    },
    {
      name: "Ensouled Scorpion Head",
      level: 1,
      experience: 454,
      link: "https://oldschool.runescape.wiki/w/Ensouled_scorpion_head",
    },
    {
      name: "Ensouled Bear Head",
      level: 1,
      experience: 480,
      link: "https://oldschool.runescape.wiki/w/Ensouled_bear_head",
    },
    {
      name: "Ensouled Unicorn Head",
      level: 1,
      experience: 494,
      link: "https://oldschool.runescape.wiki/w/Ensouled_unicorn_head",
    },
    {
      name: "Ensouled Dog Head",
      level: 1,
      experience: 520,
      link: "https://oldschool.runescape.wiki/w/Ensouled_dog_head",
    },
    {
      name: "Ensouled Chaos Druid Head",
      level: 1,
      experience: 584,
      link: "https://oldschool.runescape.wiki/w/Ensouled_chaos_druid_head",
    },
    {
      name: "Ensouled Giant Head",
      level: 1,
      experience: 650,
      link: "https://oldschool.runescape.wiki/w/Ensouled_giant_head",
    },
    {
      name: "Ensouled Ogre Head",
      level: 1,
      experience: 716,
      link: "https://oldschool.runescape.wiki/w/Ensouled_ogre_head",
    },
    {
      name: "Ensouled Elf Head",
      level: 1,
      experience: 754,
      link: "https://oldschool.runescape.wiki/w/Ensouled_elf_head",
    },
    {
      name: "Ensouled Troll Head",
      level: 1,
      experience: 780,
      link: "https://oldschool.runescape.wiki/w/Ensouled_troll_head",
    },
    {
      name: "Ensouled Horror Head",
      level: 1,
      experience: 832,
      link: "https://oldschool.runescape.wiki/w/Ensouled_horror_head",
    },
    {
      name: "Ensouled Kalphite Head",
      level: 1,
      experience: 884,
      link: "https://oldschool.runescape.wiki/w/Ensouled_kalphite_head",
    },
    {
      name: "Ensouled Dagannoth Head",
      level: 1,
      experience: 936,
      link: "https://oldschool.runescape.wiki/w/Ensouled_dagannoth_head",
    },
    {
      name: "Ensouled Bloodveld Head",
      level: 1,
      experience: 1040,
      link: "https://oldschool.runescape.wiki/w/Ensouled_bloodveld_head",
    },
    {
      name: "Ensouled Tzhaar Head",
      level: 1,
      experience: 1104,
      link: "https://oldschool.runescape.wiki/w/Ensouled_tzhaar_head",
    },
    {
      name: "Ensouled Demon Head",
      level: 1,
      experience: 1170,
      link: "https://oldschool.runescape.wiki/w/Ensouled_demon_head",
    },
    {
      name: "Ensouled Aviansie Head",
      level: 1,
      experience: 1234,
      link: "https://oldschool.runescape.wiki/w/Ensouled_aviansie_head",
    },
    {
      name: "Ensouled Abyssal Head",
      level: 1,
      experience: 1300,
      link: "https://oldschool.runescape.wiki/w/Ensouled_abyssal_head",
    },
    {
      name: "Ensouled Dragon Head",
      level: 1,
      experience: 1560,
      link: "https://oldschool.runescape.wiki/w/Ensouled_dragon_head",
    },
    {
      name: "Superior Dragon Bones",
      level: 70,
      experience: 150,
      link: "https://oldschool.runescape.wiki/w/Superior_dragon_bones",
    },
  ],
  runecrafting: [
    {
      name: "Air Rune",
      level: 1,
      experience: 5,
      link: "https://oldschool.runescape.wiki/w/Air_rune",
    },
    {
      name: "Mind Rune",
      level: 2,
      experience: 5.5,
      link: "https://oldschool.runescape.wiki/w/Mind_rune",
    },
    {
      name: "Water Rune",
      level: 5,
      experience: 6,
      link: "https://oldschool.runescape.wiki/w/Water_rune",
    },
    {
      name: "Mist Rune (Air Altar)",
      level: 6,
      experience: 8,
      link: "https://oldschool.runescape.wiki/w/Mist_rune",
    },
    {
      name: "Mist Rune (Water Altar)",
      level: 6,
      experience: 8.5,
      link: "https://oldschool.runescape.wiki/w/Mist_rune",
    },
    {
      name: "Earth Rune",
      level: 9,
      experience: 6.5,
      link: "https://oldschool.runescape.wiki/w/Earth_rune",
    },
    {
      name: "Dust Rune (Air Altar)",
      level: 10,
      experience: 8.3,
      link: "https://oldschool.runescape.wiki/w/Dust_rune",
    },
    {
      name: "Dust Rune (Earth Altar)",
      level: 10,
      experience: 9,
      link: "https://oldschool.runescape.wiki/w/Dust_rune",
    },
    {
      name: "Mud Rune (Water Altar)",
      level: 13,
      experience: 9.3,
      link: "https://oldschool.runescape.wiki/w/Mud_rune",
    },
    {
      name: "Mud Rune (Earth Altar)",
      level: 13,
      experience: 9.5,
      link: "https://oldschool.runescape.wiki/w/Mud_rune",
    },
    {
      name: "Fire Rune",
      level: 14,
      experience: 7,
      link: "https://oldschool.runescape.wiki/w/Fire_rune",
    },
    {
      name: "Smoke Rune (Air Altar)",
      level: 15,
      experience: 8.5,
      link: "https://oldschool.runescape.wiki/w/Smoke_rune",
    },
    {
      name: "Smoke Rune (Fire Altar)",
      level: 15,
      experience: 9.5,
      link: "https://oldschool.runescape.wiki/w/Smoke_rune",
    },
    {
      name: "Steam Rune (Water Altar)",
      level: 19,
      experience: 9.3,
      link: "https://oldschool.runescape.wiki/w/Steamrune",
    },
    {
      name: "Steam Rune (Fire Altar)",
      level: 19,
      experience: 10,
      link: "https://oldschool.runescape.wiki/w/Steam_rune",
    },
    {
      name: "Body Rune",
      level: 20,
      experience: 7.5,
      link: "https://oldschool.runescape.wiki/w/Body_rune",
    },
    {
      name: "Lava Rune (Earth Altar)",
      level: 23,
      experience: 10,
      link: "https://oldschool.runescape.wiki/w/Lava_rune",
    },
    {
      name: "Lava Rune (Fire Altar)",
      level: 23,
      experience: 10.5,
      link: "https://oldschool.runescape.wiki/w/Lava_rune",
    },
    {
      name: "Cosmic Rune",
      level: 27,
      experience: 8,
      link: "https://oldschool.runescape.wiki/w/Cosmic_rune",
    },
    {
      name: "Chaos Rune",
      level: 35,
      experience: 8.5,
      link: "https://oldschool.runescape.wiki/w/Chaos_rune",
    },
    {
      name: "Astral Rune",
      level: 40,
      experience: 8.7,
      link: "https://oldschool.runescape.wiki/w/Astral_rune",
    },
    {
      name: "Nature Rune",
      level: 44,
      experience: 9,
      link: "https://oldschool.runescape.wiki/w/Nature_rune",
    },
    {
      name: "Law Rune",
      level: 54,
      experience: 9.5,
      link: "https://oldschool.runescape.wiki/w/Law_rune",
    },
    {
      name: "Death Rune",
      level: 65,
      experience: 10,
      link: "https://oldschool.runescape.wiki/w/Death_rune",
    },
    {
      name: "Blood Rune",
      level: 77,
      experience: 23.8,
      link: "https://oldschool.runescape.wiki/w/Blood_rune",
    },
    {
      name: "Soul Rune",
      level: 90,
      experience: 29.7,
      link: "https://oldschool.runescape.wiki/w/Soul_rune",
    },
    {
      name: "Wrath Rune",
      level: 95,
      experience: 8,
      link: "https://oldschool.runescape.wiki/w/Wrath_rune",
    },
  ],
  smithing: [
    {
      name: "Bronze Bar",
      level: 1,
      experience: 6.2,
      link: "https://oldschool.runescape.wiki/w/Bronze_bar",
    },
    {
      name: "Bronze Dagger",
      level: 1,
      experience: 12.5,
      link: "https://oldschool.runescape.wiki/w/Bronze_dagger",
    },
    {
      name: "Bronze Sword",
      level: 4,
      experience: 12.5,
      link: "https://oldschool.runescape.wiki/w/Bronze_sword",
    },
    {
      name: "Bronze Full Helm",
      level: 7,
      experience: 25,
      link: "https://oldschool.runescape.wiki/w/Bronze_full_helm",
    },
    {
      name: "Bronze Throwing Knives",
      level: 7,
      experience: 12.5,
      link: "https://oldschool.runescape.wiki/w/Bronze_knife",
    },
    {
      name: "Bronze Kiteshield",
      level: 12,
      experience: 37.5,
      link: "https://oldschool.runescape.wiki/w/Bronze_kiteshield",
    },
    {
      name: "Bronze Platelegs / Plateskirt",
      level: 16,
      experience: 37.5,
      link: "https://oldschool.runescape.wiki/w/Bronze_platelegs",
    },
    {
      name: "Bronze Platebody",
      level: 18,
      experience: 62.5,
      link: "https://oldschool.runescape.wiki/w/Bronze_platebody",
    },
    {
      name: "Blurite Bar",
      level: 8,
      experience: 8,
      link: "https://oldschool.runescape.wiki/w/Blurite_bar",
    },
    {
      name: "Iron Bar",
      level: 15,
      experience: 12.5,
      link: "https://oldschool.runescape.wiki/w/Iron_bar",
    },
    {
      name: "Iron Dagger",
      level: 15,
      experience: 25,
      link: "https://oldschool.runescape.wiki/w/Iron_dagger",
    },
    {
      name: "Iron Sword",
      level: 19,
      experience: 25,
      link: "https://oldschool.runescape.wiki/w/Iron_sword",
    },
    {
      name: "Iron Full Helm",
      level: 22,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Iron_full_helm",
    },
    {
      name: "Iron Throwing Knives",
      level: 22,
      experience: 25,
      link: "https://oldschool.runescape.wiki/w/Iron_knife",
    },
    {
      name: "Iron Kiteshield",
      level: 27,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Iron_kiteshield",
    },
    {
      name: "Iron Platelegs / Plateskirt",
      level: 31,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Iron_platelegs",
    },
    {
      name: "Iron Platebody",
      level: 33,
      experience: 125,
      link: "https://oldschool.runescape.wiki/w/Iron_platebody",
    },
    {
      name: "Silver Bar",
      level: 20,
      experience: 13.6,
      link: "https://oldschool.runescape.wiki/w/Silver_bar",
    },
    {
      name: "Elemental Metal",
      level: 20,
      experience: 7.5,
      link: "https://oldschool.runescape.wiki/w/Elemental_metal",
    },
    {
      name: "Elemental Helmet",
      level: 20,
      experience: 20,
      link: "https://oldschool.runescape.wiki/w/Elemental_helmet",
    },
    {
      name: "Elemental Shield",
      level: 20,
      experience: 20,
      link: "https://oldschool.runescape.wiki/w/Elemental_shield",
    },
    {
      name: "Steel Bar",
      level: 30,
      experience: 17.5,
      link: "https://oldschool.runescape.wiki/w/Steel_bar",
    },
    {
      name: "Steel Dagger",
      level: 30,
      experience: 37.5,
      link: "https://oldschool.runescape.wiki/w/Steel_dagger",
    },
    {
      name: "Steel Sword",
      level: 34,
      experience: 37.5,
      link: "https://oldschool.runescape.wiki/w/Steel_sword",
    },
    {
      name: "Steel Full Helm",
      level: 37,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Steel_full_helm",
    },
    {
      name: "Steel Throwing Knives",
      level: 37,
      experience: 37.5,
      link: "https://oldschool.runescape.wiki/w/Steel_knife",
    },
    {
      name: "Steel Kiteshield",
      level: 42,
      experience: 112.5,
      link: "https://oldschool.runescape.wiki/w/Steel_kiteshield",
    },
    {
      name: "Steel Platelegs / Plateskirt",
      level: 46,
      experience: 112.5,
      link: "https://oldschool.runescape.wiki/w/Steel_platelegs",
    },
    {
      name: "Steel Platebody",
      level: 48,
      experience: 187.5,
      link: "https://oldschool.runescape.wiki/w/Steel_platebody",
    },
    {
      name: "Gold Bar",
      level: 40,
      experience: 22.5,
      link: "https://oldschool.runescape.wiki/w/Gold_bar",
    },
    {
      name: "Lovakite Bar",
      level: 45,
      experience: 20,
      link: "https://oldschool.runescape.wiki/w/Lovakite_bar",
    },
    {
      name: "Mithril Bar",
      level: 50,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Mithril_bar",
    },
    {
      name: "Mithril Dagger",
      level: 50,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Mithril_dagger",
    },
    {
      name: "Mithril Sword",
      level: 54,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Mithril_sword",
    },
    {
      name: "Mithril Full Helm",
      level: 57,
      experience: 100,
      link: "https://oldschool.runescape.wiki/w/Mithril_full_helm",
    },
    {
      name: "Mithril Throwing Knives",
      level: 57,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Mithril_knife",
    },
    {
      name: "Mithril Kiteshield",
      level: 62,
      experience: 150,
      link: "https://oldschool.runescape.wiki/w/Mithril_kiteshield",
    },
    {
      name: "Mithril Platelegs / Plateskirt",
      level: 66,
      experience: 150,
      link: "https://oldschool.runescape.wiki/w/Mithril_platelegs",
    },
    {
      name: "Mithril Platebody",
      level: 68,
      experience: 250,
      link: "https://oldschool.runescape.wiki/w/Mithril_platebody",
    },
    {
      name: "Adamantite Bar",
      level: 70,
      experience: 37.5,
      link: "https://oldschool.runescape.wiki/w/Adamantite_bar",
    },
    {
      name: "Adamant Dagger",
      level: 70,
      experience: 62.5,
      link: "https://oldschool.runescape.wiki/w/Adamant_dagger",
    },
    {
      name: "Adamant Sword",
      level: 74,
      experience: 62.5,
      link: "https://oldschool.runescape.wiki/w/Adamant_sword",
    },
    {
      name: "Adamant Full Helm",
      level: 77,
      experience: 125,
      link: "https://oldschool.runescape.wiki/w/Adamant_full_helm",
    },
    {
      name: "Adamant Throwing Knives",
      level: 77,
      experience: 62.5,
      link: "https://oldschool.runescape.wiki/w/Adamant_knife",
    },
    {
      name: "Adamant Kiteshield",
      level: 82,
      experience: 187.5,
      link: "https://oldschool.runescape.wiki/w/Adamant_kiteshield",
    },
    {
      name: "Adamant Platelegs / Plateskirt",
      level: 86,
      experience: 187.5,
      link: "https://oldschool.runescape.wiki/w/Adamant_platelegs",
    },
    {
      name: "Adamant Platebody",
      level: 88,
      experience: 312.5,
      link: "https://oldschool.runescape.wiki/w/Adamant_platebody",
    },
    {
      name: "Runite Bar",
      level: 85,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Runite_bar",
    },
    {
      name: "Rune Dagger",
      level: 85,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Rune_dagger",
    },
    {
      name: "Rune Sword",
      level: 89,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Rune_sword",
    },
    {
      name: "Rune Full Helm",
      level: 92,
      experience: 150,
      link: "https://oldschool.runescape.wiki/w/Rune_full_helm",
    },
    {
      name: "Rune Throwing Knives",
      level: 92,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Rune_knife",
    },
    {
      name: "Rune Kiteshield",
      level: 97,
      experience: 225,
      link: "https://oldschool.runescape.wiki/w/Rune_kiteshield",
    },
    {
      name: "Rune Platelegs / Plateskirt",
      level: 99,
      experience: 225,
      link: "https://oldschool.runescape.wiki/w/Rune_platelegs",
    },
    {
      name: "Rune Platebody",
      level: 99,
      experience: 375,
      link: "https://oldschool.runescape.wiki/w/Rune_platebody",
    },
  ],
  slayer: [],
  thieving: [
    {
      name: "Pickpocket Man",
      level: 1,
      experience: 8,
      link: "https://oldschool.runescape.wiki/w/Man",
    },
    {
      name: "Vegetable Stall",
      level: 2,
      experience: 10,
      link: "https://oldschool.runescape.wiki/w/Vegetable_stall",
    },
    {
      name: "Bakery Stall",
      level: 5,
      experience: 16,
      link: "https://oldschool.runescape.wiki/w/Bakery_stall",
    },
    {
      name: "Crafting Stall",
      level: 5,
      experience: 16,
      link: "https://oldschool.runescape.wiki/w/Crafting_stall",
    },
    {
      name: "Tea Stall",
      level: 5,
      experience: 16,
      link: "https://oldschool.runescape.wiki/w/Tea_stall",
    },
    {
      name: "Pickpocket Farmer",
      level: 10,
      experience: 14.5,
      link: "https://oldschool.runescape.wiki/w/Farmer",
    },
    {
      name: "Pickpocket Female H.A.M.",
      level: 15,
      experience: 18.5,
      link: "https://oldschool.runescape.wiki/w/Female_H.A.M._member",
    },
    {
      name: "Pickpocket Male H.A.M.",
      level: 20,
      experience: 22.5,
      link: "https://oldschool.runescape.wiki/w/Male_H.A.M._member",
    },
    {
      name: "Silk Stall",
      level: 20,
      experience: 24,
      link: "https://oldschool.runescape.wiki/w/Silk_stall",
    },
    {
      name: "Wine Stall",
      level: 22,
      experience: 27,
      link: "https://oldschool.runescape.wiki/w/Wine_stall",
    },
    {
      name: "Fruit Stall",
      level: 25,
      experience: 28.2,
      link: "https://oldschool.runescape.wiki/w/Fruit_Stall",
    },
    {
      name: "Seed Stall",
      level: 27,
      experience: 10,
      link: "https://oldschool.runescape.wiki/w/Seed_stall",
    },
    {
      name: "Pickpocket Rogue",
      level: 32,
      experience: 35.5,
      link: "https://oldschool.runescape.wiki/w/Rogue",
    },
    {
      name: "Pickpocket Cave Goblin",
      level: 36,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Cave_goblin",
    },
    {
      name: " Pickpocket Master Farmer",
      level: 38,
      experience: 43,
      link: "https://oldschool.runescape.wiki/w/Master_Farmer",
    },
    {
      name: "Pickpocket Guard",
      level: 40,
      experience: 46.8,
      link: "https://oldschool.runescape.wiki/w/Guard",
    },
    {
      name: "Fish Stall",
      level: 42,
      experience: 42,
      link: "https://oldschool.runescape.wiki/w/Fish_stall",
    },
    {
      name: "Steal Cave Goblin Wire",
      level: 44,
      experience: 22,
      link: "https://oldschool.runescape.wiki/w/Cave_goblin_wire",
    },
    {
      name: "Blackjack Bearded Bandit",
      level: 45,
      experience: 65,
      link: "https://oldschool.runescape.wiki/w/Bearded_Pollnivnian_Bandit",
    },
    {
      name: "Pickpocket Fremennik Citizen",
      level: 45,
      experience: 65,
      link: "https://oldschool.runescape.wiki/w/Fremennik_Citizen",
    },
    {
      name: "Crossbow Stall",
      level: 49,
      experience: 52,
      link: "https://oldschool.runescape.wiki/w/Crossbow_stall",
    },
    {
      name: "Silver Stall",
      level: 50,
      experience: 54,
      link: "https://oldschool.runescape.wiki/w/Silver_stall",
    },
    {
      name: "Pickpocket Knight of Ardougne",
      level: 55,
      experience: 84.3,
      link: "https://oldschool.runescape.wiki/w/Knight_of_Ardougne",
    },
    {
      name: "Spice Stall",
      level: 65,
      experience: 81,
      link: "https://oldschool.runescape.wiki/w/Spice_stall",
    },
    {
      name: "Pickpocket Paladin",
      level: 70,
      experience: 151.7,
      link: "https://oldschool.runescape.wiki/w/Paladin",
    },
    {
      name: "Gem Stall",
      level: 75,
      experience: 160,
      link: "https://oldschool.runescape.wiki/w/Gem_stall",
    },
    {
      name: "Pickpocket Gnome",
      level: 75,
      experience: 198.5,
      link: "https://oldschool.runescape.wiki/w/Gnome",
    },
    {
      name: "Pickpocket Hero",
      level: 80,
      experience: 275,
      link: "https://oldschool.runescape.wiki/w/Hero",
    },
    {
      name: "Ore Stall",
      level: 82,
      experience: 180,
      link: "https://oldschool.runescape.wiki/w/Ore_stall",
    },
    {
      name: "Pickpocket Elf",
      level: 85,
      experience: 353,
      link: "https://oldschool.runescape.wiki/w/Elf_(Thieving)",
    },
    {
      name: "Pickpocket TzHaar-Hur",
      level: 90,
      experience: 103.4,
      link: "https://oldschool.runescape.wiki/w/TzHaar-Hur",
    },
  ],
  woodcutting: [
    {
      name: "Logs",
      level: 1,
      experience: 25,
      link: "https://oldschool.runescape.wiki/w/Logs",
    },
    {
      name: "Oak Logs",
      level: 15,
      experience: 37.5,
      link: "https://oldschool.runescape.wiki/w/Oak_logs",
    },
    {
      name: "Willow Logs",
      level: 30,
      experience: 67.5,
      link: "https://oldschool.runescape.wiki/w/Willow_logs",
    },
    {
      name: "Teak Logs",
      level: 35,
      experience: 85,
      link: "https://oldschool.runescape.wiki/w/Teak_logs",
    },
    {
      name: "Maple Logs",
      level: 45,
      experience: 100,
      link: "https://oldschool.runescape.wiki/w/Maple_logs",
    },
    {
      name: "Mahogany Logs",
      level: 50,
      experience: 125,
      link: "https://oldschool.runescape.wiki/w/Mahogany_logs",
    },
    {
      name: "Yew Logs",
      level: 60,
      experience: 175,
      link: "https://oldschool.runescape.wiki/w/Yew_logs",
    },
    {
      name: "Magic Logs",
      level: 75,
      experience: 250,
      link: "https://oldschool.runescape.wiki/w/Magic_logs",
    },
    {
      name: "Redwood Logs",
      level: 90,
      experience: 380,
      link: "https://oldschool.runescape.wiki/w/Redwood_logs",
    },
  ],
};

export default skills;
