const skills = {
  agility: [
    {
      name: "Gnome Stronghold Agility Course",
      level: 1,
      experience: 86.5,
      link:
        "https://oldschool.runescape.wiki/w/Gnome_Stronghold_Agility_Course",
    },
    {
      name: "Draynor Village Rooftop Course",
      level: 10,
      experience: 120,
      link: "https://oldschool.runescape.wiki/w/Draynor_Village_Rooftop_Course",
    },
    {
      name: "Al Kharid Rooftop Course",
      level: 20,
      experience: 180,
      link: "https://oldschool.runescape.wiki/w/Al_Kharid_Rooftop_Course",
    },
    {
      name: "Werewolf Skullball",
      level: 25,
      experience: 750,
      link: "https://oldschool.runescape.wiki/w/Werewolf_Skullball",
    },
    {
      name: "Varrock Rooftop Course",
      level: 30,
      experience: 238,
      link: "https://oldschool.runescape.wiki/w/Varrock_Rooftop_Course",
    },
    {
      name: "Penguin Agility Course",
      level: 30,
      experience: 540,
      link: "https://oldschool.runescape.wiki/w/Penguin_Agility_Course",
    },
    {
      name: "Agility Pyramid",
      level: 30,
      experience: 1030,
      link: "https://oldschool.runescape.wiki/w/Agility_Pyramid",
    },
    {
      name: "Barbarian Outpost Agility Course",
      level: 35,
      experience: 153.3,
      link:
        "https://oldschool.runescape.wiki/w/Barbarian_Outpost_Agility_Course",
    },
    {
      name: "Canifis Rooftop Course",
      level: 40,
      experience: 240,
      link: "https://oldschool.runescape.wiki/w/Canifis_Rooftop_Course",
    },
    {
      name: "Ape Atoll Agility Course",
      level: 48,
      experience: 580,
      link: "https://oldschool.runescape.wiki/w/Ape_Atoll_Agility_Course",
    },
    {
      name: "Falador Rooftop Course",
      level: 50,
      experience: 440,
      link: "https://oldschool.runescape.wiki/w/Falador_Rooftop_Course",
    },
    {
      name: "Wilderness Agility Course",
      level: 52,
      experience: 571.4,
      link: "https://oldschool.runescape.wiki/w/Wilderness_Agility_Course",
    },
    {
      name: "Seers' Village Rooftop Course",
      level: 60,
      experience: 570,
      link:
        "https://oldschool.runescape.wiki/w/Seers%27_Village_Rooftop_Course",
    },
    {
      name: "Werewolf Agility Course",
      level: 60,
      experience: 730,
      link: "https://oldschool.runescape.wiki/w/Werewolf_Agility_Course",
    },
    {
      name: "Pollnivneach Rooftop Course",
      level: 70,
      experience: 890,
      link: "https://oldschool.runescape.wiki/w/Pollnivneach_Rooftop_Course",
    },
    {
      name: "Dorgesh-Kaan Agility Course",
      level: 70,
      experience: 2750,
      link: "https://oldschool.runescape.wiki/w/Dorgesh-Kaan_Agility_Course",
    },
    {
      name: "Prifddinas Agility Course",
      level: 75,
      experience: 1285.2,
      link: "https://oldschool.runescape.wiki/w/Prifddinas_Agility_Course",
    },
    {
      name: "Rellekka Rooftop Course",
      level: 80,
      experience: 780,
      link: "https://oldschool.runescape.wiki/w/Rellekka_Rooftop_Course",
    },
    {
      name: "Ardougne Rooftop Course",
      level: 90,
      experience: 793,
      link: "https://oldschool.runescape.wiki/w/Ardougne_Rooftop_Course",
    },
  ],
  construction: [
    {
      name: "",
      level: 0,
      experience: 0,
      link: "",
    },
  ],
  cooking: [
    {
      name: "Anchovies",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Anchovies",
    },
    {
      name: "Cooked Chicken",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Cooked_chicken",
    },
    {
      name: "Cooked Meat",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Cooked_meat",
    },
    {
      name: "Cooked Rabbit",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Cooked_rabbit",
    },
    {
      name: "Shrimps",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Shrimps",
    },
    {
      name: "Bread",
      level: 1,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Bread",
    },
    {
      name: "Sardine",
      level: 1,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Sardine",
    },
    {
      name: "Herring",
      level: 5,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Herring",
    },
    {
      name: "Fruit Blast",
      level: 6,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Fruit_blast",
    },
    {
      name: "Baked Potato",
      level: 7,
      experience: 15,
      link: "https://oldschool.runescape.wiki/w/Baked_potato",
    },
    {
      name: "Mackerel",
      level: 10,
      experience: 60,
      link: "https://oldschool.runescape.wiki/w/Mackerel",
    },
    {
      name: "Redberry Pie",
      level: 10,
      experience: 78,
      link: "https://oldschool.runescape.wiki/w/Redberry_pie",
    },
    {
      name: "Trout",
      level: 15,
      experience: 70,
      link: "https://oldschool.runescape.wiki/w/Trout",
    },
    {
      name: "Cod",
      level: 18,
      experience: 75,
      link: "https://oldschool.runescape.wiki/w/Cod",
    },
    {
      name: "Pike",
      level: 20,
      experience: 80,
      link: "https://oldschool.runescape.wiki/w/Pike",
    },
    {
      name: "Meat Pie",
      level: 20,
      experience: 104,
      link: "https://oldschool.runescape.wiki/w/Meat_pie",
    },
    {
      name: "Salmon",
      level: 25,
      experience: 90,
      link: "https://oldschool.runescape.wiki/w/Salmon",
    },
    {
      name: "Stew",
      level: 25,
      experience: 117,
      link: "https://oldschool.runescape.wiki/w/Stew",
    },
    {
      name: "Tuna",
      level: 30,
      experience: 100,
      link: "https://oldschool.runescape.wiki/w/Tuna",
    },
    {
      name: "Apple Pie",
      level: 30,
      experience: 130,
      link: "https://oldschool.runescape.wiki/w/Apple_pie",
    },
    {
      name: "Cooked Karambwan",
      level: 30,
      experience: 190,
      link: "https://oldschool.runescape.wiki/w/Cooked_karambwan",
    },
    {
      name: "Plain Pizza",
      level: 35,
      experience: 143,
      link: "https://oldschool.runescape.wiki/w/Plain_pizza",
    },
    {
      name: "Jug of Wine",
      level: 35,
      experience: 200,
      link: "https://oldschool.runescape.wiki/w/Jug_of_wine",
    },
    {
      name: "Potato with Butter",
      level: 39,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Potato_with_butter",
    },
    {
      name: "Lobster",
      level: 40,
      experience: 120,
      link: "https://oldschool.runescape.wiki/w/Lobster",
    },
    {
      name: "Cake",
      level: 40,
      experience: 180,
      link: "https://oldschool.runescape.wiki/w/Cake",
    },
    {
      name: "Swordfish",
      level: 45,
      experience: 140,
      link: "https://oldschool.runescape.wiki/w/Swordfish",
    },
    {
      name: "Meat Pizza",
      level: 45,
      experience: 169,
      link: "https://oldschool.runescape.wiki/w/Meat_pizza",
    },
    {
      name: "Potato with Cheese",
      level: 47,
      experience: 40,
      link: "https://oldschool.runescape.wiki/w/Potato_with_cheese",
    },
    {
      name: "Chocolate Cake",
      level: 50,
      experience: 210,
      link: "https://oldschool.runescape.wiki/w/Chocolate_cake",
    },
    {
      name: "Anchovy Pizza",
      level: 55,
      experience: 182,
      link: "https://oldschool.runescape.wiki/w/Anchovy_pizza",
    },
    {
      name: "Monkfish",
      level: 62,
      experience: 150,
      link: "https://oldschool.runescape.wiki/w/Monkfish",
    },
    {
      name: "Pineapple Pizza",
      level: 65,
      experience: 195,
      link: "https://oldschool.runescape.wiki/w/Pineapple_pizza",
    },
    {
      name: "Wine Of Zamorak",
      level: 65,
      experience: 200,
      link: "https://oldschool.runescape.wiki/w/Wine_of_zamorak",
    },
    {
      name: "Shark",
      level: 80,
      experience: 210,
      link: "https://oldschool.runescape.wiki/w/Shark",
    },
    {
      name: "Anglerfish",
      level: 84,
      experience: 230,
      link: "https://oldschool.runescape.wiki/w/Anglerfish",
    },
    {
      name: "Manta Ray",
      level: 91,
      experience: 216.2,
      link: "https://oldschool.runescape.wiki/w/Manta_ray",
    },
  ],
  crafting: [],
  farming: [],
  firemaking: [],
  fishing: [],
  fletching: [],
  herblore: [],
  hunter: [],
  magic: [],
  melee: [],
  mining: [],
  prayer: [
    {
      name: "Bones",
      level: 1,
      experience: 4.5,
      link: "https://oldschool.runescape.wiki/w/Bones",
    },
    {
      name: "Monkey Bones",
      level: 1,
      experience: 5,
      link: "https://oldschool.runescape.wiki/w/Monkey_bones",
    },
    {
      name: "Bat Bones",
      level: 1,
      experience: 5.3,
      link: "https://oldschool.runescape.wiki/w/Bat_bones",
    },
    {
      name: "Big Bones",
      level: 1,
      experience: 15,
      link: "https://oldschool.runescape.wiki/w/Big_bones",
    },
    {
      name: "Jogre Bones",
      level: 1,
      experience: 15,
      link: "https://oldschool.runescape.wiki/w/Jogre_bones",
    },
    {
      name: "Zogre Bones",
      level: 1,
      experience: 22.5,
      link: "https://oldschool.runescape.wiki/w/Zogre_bones",
    },
    {
      name: "Shaikahan Bones",
      level: 1,
      experience: 25,
      link: "https://oldschool.runescape.wiki/w/Shaikahan_bones",
    },
    {
      name: "Babydragon Bones",
      level: 1,
      experience: 30,
      link: "https://oldschool.runescape.wiki/w/Babydragon_bones",
    },
    {
      name: "Wyrm Bones",
      level: 1,
      experience: 50,
      link: "https://oldschool.runescape.wiki/w/Wyrm_bones",
    },
    {
      name: "Dragon Bones",
      level: 1,
      experience: 72,
      link: "https://oldschool.runescape.wiki/w/Dragon_bones",
    },
    {
      name: "Wyvern Bones",
      level: 1,
      experience: 72,
      link: "https://oldschool.runescape.wiki/w/Wyvern_bones",
    },
    {
      name: "Drake Bones",
      level: 1,
      experience: 80,
      link: "https://oldschool.runescape.wiki/w/Drake_bones",
    },
    {
      name: "Fayrg Bones",
      level: 1,
      experience: 84,
      link: "https://oldschool.runescape.wiki/w/Fayrg_bones",
    },
    {
      name: "Lava Dragon Bones",
      level: 1,
      experience: 85,
      link: "https://oldschool.runescape.wiki/w/Lava_dragon_bones",
    },
    {
      name: "Raurg Bones",
      level: 1,
      experience: 96,
      link: "https://oldschool.runescape.wiki/w/Raurg_bones",
    },
    {
      name: "Hydra Bones",
      level: 1,
      experience: 110,
      link: "https://oldschool.runescape.wiki/w/Hydra_bones",
    },
    {
      name: "Dagannoth Bones",
      level: 1,
      experience: 125,
      link: "https://oldschool.runescape.wiki/w/Dagannoth_bones",
    },
    {
      name: "Ourg Bones",
      level: 1,
      experience: 140,
      link: "https://oldschool.runescape.wiki/w/Ourg_bones",
    },
    {
      name: "Ensouled Goblin Head",
      level: 1,
      experience: 130,
      link: "https://oldschool.runescape.wiki/w/Ensouled_goblin_head",
    },
    {
      name: "Ensouled Monkey Head",
      level: 1,
      experience: 182,
      link: "https://oldschool.runescape.wiki/w/Ensouled_monkey_head",
    },
    {
      name: "Ensouled Imp Head",
      level: 1,
      experience: 286,
      link: "https://oldschool.runescape.wiki/w/Ensouled_imp_head",
    },
    {
      name: "Ensouled Minotaur Head",
      level: 1,
      experience: 364,
      link: "https://oldschool.runescape.wiki/w/Ensouled_minotaur_head",
    },
    {
      name: "Ensouled Scorpion Head",
      level: 1,
      experience: 454,
      link: "https://oldschool.runescape.wiki/w/Ensouled_scorpion_head",
    },
    {
      name: "Ensouled Bear Head",
      level: 1,
      experience: 480,
      link: "https://oldschool.runescape.wiki/w/Ensouled_bear_head",
    },
    {
      name: "Ensouled Unicorn Head",
      level: 1,
      experience: 494,
      link: "https://oldschool.runescape.wiki/w/Ensouled_unicorn_head",
    },
    {
      name: "Ensouled Dog Head",
      level: 1,
      experience: 520,
      link: "https://oldschool.runescape.wiki/w/Ensouled_dog_head",
    },
    {
      name: "Ensouled Chaos Druid Head",
      level: 1,
      experience: 584,
      link: "https://oldschool.runescape.wiki/w/Ensouled_chaos_druid_head",
    },
    {
      name: "Ensouled Giant Head",
      level: 1,
      experience: 650,
      link: "https://oldschool.runescape.wiki/w/Ensouled_giant_head",
    },
    {
      name: "Ensouled Ogre Head",
      level: 1,
      experience: 716,
      link: "https://oldschool.runescape.wiki/w/Ensouled_ogre_head",
    },
    {
      name: "Ensouled Elf Head",
      level: 1,
      experience: 754,
      link: "https://oldschool.runescape.wiki/w/Ensouled_elf_head",
    },
    {
      name: "Ensouled Troll Head",
      level: 1,
      experience: 780,
      link: "https://oldschool.runescape.wiki/w/Ensouled_troll_head",
    },
    {
      name: "Ensouled Horror Head",
      level: 1,
      experience: 832,
      link: "https://oldschool.runescape.wiki/w/Ensouled_horror_head",
    },
    {
      name: "Ensouled Kalphite Head",
      level: 1,
      experience: 884,
      link: "https://oldschool.runescape.wiki/w/Ensouled_kalphite_head",
    },
    {
      name: "Ensouled Dagannoth Head",
      level: 1,
      experience: 936,
      link: "https://oldschool.runescape.wiki/w/Ensouled_dagannoth_head",
    },
    {
      name: "Ensouled Bloodveld Head",
      level: 1,
      experience: 1040,
      link: "https://oldschool.runescape.wiki/w/Ensouled_bloodveld_head",
    },
    {
      name: "Ensouled Tzhaar Head",
      level: 1,
      experience: 1104,
      link: "https://oldschool.runescape.wiki/w/Ensouled_tzhaar_head",
    },
    {
      name: "Ensouled Demon Head",
      level: 1,
      experience: 1170,
      link: "https://oldschool.runescape.wiki/w/Ensouled_demon_head",
    },
    {
      name: "Ensouled Aviansie Head",
      level: 1,
      experience: 1234,
      link: "https://oldschool.runescape.wiki/w/Ensouled_aviansie_head",
    },
    {
      name: "Ensouled Abyssal Head",
      level: 1,
      experience: 1300,
      link: "https://oldschool.runescape.wiki/w/Ensouled_abyssal_head",
    },
    {
      name: "Ensouled Dragon Head",
      level: 1,
      experience: 1560,
      link: "https://oldschool.runescape.wiki/w/Ensouled_dragon_head",
    },
    {
      name: "Superior Dragon Bones",
      level: 70,
      experience: 150,
      link: "https://oldschool.runescape.wiki/w/Superior_dragon_bones",
    },
  ],
  ranged: [],
  runecrafting: [],
  smithing: [],
  slayer: [],
  thieving: [],
  woodcutting: [],
};

export default skills;
